### ISSUE TITLE
Node 11 support

### ISSUE THREAD

**Issue by christhegrand** [elastic/apm-nodejs-http-client#103]
Does this library not work with Node 11? I get a yarn error when trying to install elastic-apm-node 3.3.0 with yarn when using Node 11.14.0, but I would expect the library to work under Node 11 if it works with Node 10 and 12:

```
sensorium:bagel yarn add elastic-apm-node
yarn add v1.15.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error elastic-apm-http-client@9.3.0: The engine "node" is incompatible with this module. Expected version "^8.6.0 || 10 || >=12". Got "11.14.0"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
sensorium:bagel node -v
v11.14.0
```

**Comment by alemagio** [comment]
Hi, i'm not a mantainer of the project
Anyway if you look at the package.json you can see this line:

`
"engines": {
    "node": "^8.6.0 || 10 || >=12"
  },
`

So i guess node 11 is not supported

**Comment by watson** [comment]
Correct. Version 9.0.0+ of this module no longer supports Node.js 11 as it's no longer supported by the Node.js community. Node.js 11 went out of maintenance in the first half of 2019 and it's no longer recommended to run Node.js 11 in production. For details see the Node.js releases page: https://nodejs.org/en/about/releases/

Node.js 10 and 12 are what's called LTS releases and have a much longer support lifecycle.
