### ISSUE TITLE
Cannot get this to send out spans

### ISSUE THREAD

**Issue by stefandec** [elastic/apm-nodejs-http-client#108]
I am sorry if I post this in the wrong way, or to the wrong forum. But I cannot get this package to work. Here is my complete node.js program:

**const Client = require('elastic-apm-http-client')
const options = {
    agentName: 'my-nodejs-agent',
    agentVersion: require('elastic-apm-http-client/package.json').version,
    serviceName: 'Hybrid_cloudflow_jackets',
    serviceVersion : '1.0.0',
    userAgent: 'Hybrid Custom Elastic APM Agent',
    secretToken: 'XXXXXXXXX',
    serverUrl: 'https://528e6f7cd510472591f55b07d0d68130.apm.eu-west-3.aws.elastic-cloud.com',
    payloadLogFile : 'test_apm_debug.log'
};
const client = new Client(options);
const span = {  name: 'SELECT FROM users',   duration: 42,     start: 0,  type: 'db.mysql.query'   }
client.sendSpan(span)
client.sendSpan(span)
console.log(`driver reported ${client.sent} records sent`)
client.flush();
console.log(`after flush: driver reported ${client.sent} records sent`)
client.end();
client.destroy();**

Running this gives the following output:
C:\Program Files\nodejs\node.exe .\test_apm.js
**driver reported 0 records sent**
after flush: driver reported 0 records sent

Also, the logfile is empty (as is to be expected)
Please help, 
Thank you so much in advance

**Comment by marekduciuc** [comment]
Hello,
The way client.sent is used here is wrong, client sends the data using streams and its not synchronous, so logging on the next line won't guarantee anything.
```
client.sendSpan(span, () => {
  // can be logged here
})
client.flush(() => {
   // log here
})
```

Using it in the above way guarantees, the users code runs after the client performed the action.  Check the API for more details https://github.com/elastic/apm-nodejs-http-client/tree/1526dedc26392bd92f20b5079f848c7e77567e7c#clientsendspanspan-callback (edited)

**Comment by stefandec** [comment]
thank you for your reaction. If I read this correctly, you are saying that it will (eventually) send the records, but I only get correct feedback in the callback routines. I would have expected the flush to do synchronous flush, but that was a mistake.
Thanks
