### ISSUE TITLE
Non-standard indentation and undefined catch scope

### ISSUE THREAD

**Issue by robertosousa1** [elastic/apm-nodejs-http-client#119]
In the file "lib/ndjson.js" the tryJSONStringify function is declared below your call, this causes an "Expected to return a value at the end of function 'tryJSONStringify' indentation conflict" and this function still has nothing defined in its catch scope.

I suggest implementing the following code:
```
'use strict'

const stringify = require('fast-safe-stringify')

function tryJSONStringify (obj) {
  try {
    return JSON.stringify(obj)
  } catch (e) {
    throw new Error('Error when running tryJSONStringify')
  }
}

exports.serialize = function serialize (obj) {
  const str = tryJSONStringify(obj) || stringify(obj)
  return str + '\n'
}

```

**Comment by astorm** [comment]
@robertosousa1 Thanks for the bug report @robertosousa1 -- when you say you're seeing the error

> expected to return a value at the end of function 'tryJSONStringify' indentation conflict"

Is this an error you see while running the agent?  Or is this a linting error related to the other issues you've opened?

**Comment by K-Kumar-01** [comment]
@astorm 
Is the issue still open?
If yes then can I make a pr for the issue?

**Comment by astorm** [comment]
@K-Kumar-01 We're still waiting on @robertosousa1 -- when he said 

> expected to return a value at the end of function 'tryJSONStringify' indentation conflict"

it wasn't clear whether this was a linting error or an "execution of code during the agent error".  

@k-g-elastic Can you reproduce the error @robertosousa1 mentioned?  If so, can you share those reproduction steps?

**Comment by robertosousa1** [comment]
Hi @astorm,

It is a linting error.

If you understand that there is a need for adjustment, I can do the PR.

**Comment by trentm** [comment]
Hi All,

From what linting tool do you see this linting error?  This repo is currently using [standard](https://standardjs.com/) for linting and that passes:

```
[apm-nodejs-http-client (git:master)]% npx standard
```

Note that we don't want to change this to throw an error in the `catch` block. Perhaps explicitly returning undefined in the catch block would pass your linter and be more explicit.  I'd welcome a PR doing that.

**Comment by trentm** [comment]
In https://github.com/elastic/apm-agent-nodejs/pull/3507 this repo code was moved to https://github.com/elastic/apm-agent-nodejs/tree/main/lib/apm-client/http-apm-client/.  I'm closing this issue here. FWIW this code passes the eslint linting we are using.  Please feel free to open a PR on the apm-agent-nodejs.git repo if you need some change to satisfy another linter you are using.
