### ISSUE TITLE
Need to increment git ignore configuration

### ISSUE THREAD

**Issue by robertosousa1** [elastic/apm-nodejs-http-client#121]
It is a good practice to increase the configuration of .gitignore with files that have no direct value to the application in addition.

For example, add the following files:
yarn.lock
logs
.log
npm-debug.log
pids
*.pid
*.seed
.idea

**Comment by JCMais** [comment]
About `yarn.lock`: [Lockfiles should be committed on all projects
](https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/)

**Comment by robertosousa1** [comment]
@JCMais I understand and as for the other files, does the suggestion seem interesting?

**Comment by robertosousa1** [comment]
In an open issue in the 'elasticsearch-js' repo it is said that it is not a good practice to store files 'package-lock.json' which is the equivalent of 'yarn.lock' in libraries, it is a good practice only for applications.

**Comment by astorm** [comment]
Thanks for the suggestion @robertosousa1 and for the discussion @JCMais -- it's always nice to hear from the community.  

That said -- we prefer to grow our `.gitignore` files organically based on the needs of folks on the team or folks making contributions.   If you run into a file that's a problem for your workflow, just add it to the `.gitignore` file when you make your PR. 

(as a side note -- there's no right answers as to whether to include package manager `lock` files or not -- it depends on what you're doing and who your project is serving)

**Comment by robertosousa1** [comment]
I understand. Thanks!!!
