### ISSUE TITLE
CI implementations (in GitHub actions and Jenkinis) duplicate the number of builds per PR

### ISSUE THREAD

**Issue by v1v** [elastic/apm-nodejs-http-client#173]
### What

If GitHub actions produce the same outcome that the JenkinsCI pipeline, then can it be removed?

### Why

- Duplicated effort to maintain the same implementation in two different CI.
- JenkinsCI is the official CI.
- Builds cost twice.
- Observing the CI/CD with Jenkins is something we have in place.
- Get for free all the tooling we have in place and will put in place to improve the Development eXperience.
- Observability Onboarding, the same development experience for everyone at Elastic who contributes to the observability solution.

### Issues

The first implementation was done in Jenkins in https://github.com/elastic/apm-nodejs-http-client/pull/65

And the GitHub actions in https://github.com/elastic/apm-nodejs-http-client/pull/123

**Comment by astorm** [comment]
Capturing an offline conversion with @AlexanderWert on this (-- and, in case it's not obvious, this is the start of a conversation :)).

Our intention for now is to keep both the Jenkins CI and the GitHub Actions CI (GHA) running.  While the Jenkins tests do offer a number of company wide benefits and are clearly valuable, there's a few import things that GHA do for us that help immensely with day-to-day development. 

The two biggest one are

1. Speed: The GHA tests tend to run faster/more-performantly than the full Jenkins suites do.  This is invaluable in the dev/test/dev-again cycle.  Without them our productivity would suffer. 

2. Public Access: The Jenkins tests will not run for third parties without intervention from an elastic employee.  This means the jenkins tests are effectively not there for folks wanting to make PRs

**Comment by trentm** [comment]
Jenkins support was removed in #194
