### ISSUE TITLE
Change truncate algorithm?

### ISSUE THREAD

**Issue by watson** [elastic/apm-nodejs-http-client#38]
We currently have a pretty sophisticated truncate algorithm that will ensure that the truncated string isn't above a certain threshold measured in bytes, but it's clever enough to not cut a string in the middle of a unicode character. If the truncation point happens to in the middle of the a unicode character, it will instead drop that character and truncate just before it. This ensures that we can guarantee that the string is never longer than the a given size in bytes.

This however is different from how string max lengths is measured by the JSON Schema used by the APM Server and how Elasticsearch limits strings. Here, the limit is measured in characters and not in bytes.

It's my understanding that the other agents also truncate based on characters and not bytes.

So while I think our truncation algorithm is superior, to align with the rest of the stack and with the other agents, we should consider counting chars instead of bytes.

**Comment by alemagio** [comment]
Hi, i guess to solve this I could just see what's the algorithm used by Elasticsearch or the APM server right and apply it to out case right?

**Comment by trentm** [comment]
This was done a while back as part of https://github.com/elastic/apm-nodejs-http-client/pull/162
