### ISSUE TITLE
Truncate keys

### ISSUE THREAD

**Issue by watson** [elastic/apm-nodejs-http-client#41]
Today we just truncate object values, but we should probably truncate keys with the same algorithm we use to truncate values.

**Comment by alemagio** [comment]
Hi, i would like to work on this.
I think that i should work on the truncate.js file and use the onObject callback (where i have access to the key) instead of the onValue (which is the one truncating now).
Right?

**Comment by Qard** [comment]
It might be achievable with `onObject`. It could be a bit of a challenge though as it's a bit tough to wrap your brain around the nested filter stuff--you could very easily blow away your own changes or send it into an infinite loop and blow the stack. Feel free to ask questions here if you get stuck and I'll do what I can to help. 👍

**Comment by alemagio** [comment]
Hi, i started looking for this and I'm not sure what the expectation is.
If I take as an expample the truncateSpan function you expect that, given an input span like this:
{
    foo: "bar",
}
and an option that sets the max key length to 2 the output should be:
{
    fo: "bar",
}
Correct?

**Comment by Qard** [comment]
Yes. Recursively, all keys should be shortened. One challenge that we never put much thought into how to handle is what to do about collisions. For example, shortening `a1` and `a2` to key length 1 would result in two different values for the same key--which one should it finally be? I'm not really sure. 🤔

**Comment by watson** [comment]
I would consider just truncating the keys that are controlled by the user. Might be easier on the CPU

**Comment by alemagio** [comment]
Ok, but the issue regarding the collisions remains right?

**Comment by Qard** [comment]
Yes, collisions are still possible.

**Comment by alemagio** [comment]
Just created a PR
It is not complete yet but i think it could be useful to make me understand if i'm on the right way 
Let me know ;)

**Comment by Qard** [comment]
Closed by #92.
