### ISSUE TITLE
Truncate Mutates Context Data

### ISSUE THREAD

**Issue by blakeembrey** [elastic/apm-nodejs-http-client#46]
When using Elastic APM, any data being logged is mutated during the filter execution of `truncate`. This occurred when I tried to use APM with AWS Lambda. The `result` of the lambda function is attached to the context in https://github.com/elastic/apm-agent-nodejs/blob/abb4f1af4a39e59415bf8977608d928e29e11c72/lib/lambda.js#L45, and this client mutates the output object as a result trimming all headers and the body to 1024 bytes. This results in an invalid AWS lambda response.

**Comment by LucGranato** [comment]
This gave me a brain aneurysm.
Lucky that APM was the only thing that was different between the local test and the production environment. It was easier to guess...
