### ISSUE TITLE
Update remote config logic to match status code change

### ISSUE THREAD

**Issue by watson** [elastic/apm-nodejs-http-client#71]
If no remote config is set up for the given agent/environment, the APM Server [now returns](https://github.com/elastic/apm-server/pull/2458) 200 with an empty object instead of 404. This wrongly triggers the `config` event.

Our agent currently handles this ok, but it would still be best if we didn't emit the `config` event.

**Comment by watson** [comment]
We probably want to allow for users of this module to fall back to the old value of a config option previously configured via central config, in case the configuration for the given agent/environment is removed in Kibana.

So if we change the behavior to not emit a config object when it's empty, they will not know it has been deleted. So I propose we keep the current behavior and just update the code comments and `README.md` to explain this.

@Qard what do you think about this?

**Comment by Qard** [comment]
Sounds reasonable.
