### ISSUE TITLE
Add Node.js runtime name + version to user-agent string

### ISSUE THREAD

**Issue by watson** [elastic/apm-nodejs-http-client#72]
We should add `node/{version}` to the end of the user-agent string, e.g `node/12.4.1`:

```
${process.release.name}/${process.versions.node}
```

**Comment by alemagio** [comment]
Hi, i would like to work on this but it seems already resolved, am i looking in the wrong place maybe?

**Comment by watson** [comment]
It's still not resolved so your help would be very welcome 😃 

Currently, only the name and version from the `package.json` file is added - not the Node.js name and version. Maybe that's what you saw?

I think it would make sense to add it to the end of this line: https://github.com/elastic/apm-nodejs-http-client/blob/bc687bf150440ec6b9683c3d77d4773da0e6944e/index.js#L532

(you could probably update it to a template string now that you're at it also)

**Comment by alemagio** [comment]
[https://github.com/elastic/apm-nodejs-http-client/pull/76](url)

PR created
